automation:
    - id: '1234567654321'
      alias: Webhook-in-comandi
      description: ''
      triggers:
      - trigger: webhook
        allowed_methods:
        - POST
        - PUT
        local_only: true
        webhook_id: !secret webhook_id_in
      conditions: []
      actions:
      - data:
          value: '{{ trigger.json }}'
        action: input_text.set_value
        target:
          entity_id: input_text.rx
      - data:
          value: '{{ trigger.json.password }}'
        action: input_text.set_value
        target:
          entity_id: input_text.password
      - data:
          value: '{{ trigger.json.azione }}'
        action: input_text.set_value
        target:
          entity_id: input_text.azione
      - data:
          value: '{{ trigger.json.numero }}'
        action: input_text.set_value
        target:
          entity_id: input_text.numero
      - action: script.comandi_aree
        data: {}
      - action: script.comandi_uscite
        data: {}
      - action: script.comandi_zone_filo
        data: {}
      - action: script.comandi_zone_filo_non_pronta_pronta
        data: {}
      - action: script.comandi_zone_filo_allarme_no_allarme
        data: {}
      - action: script.comandi_zone_radio
        data: {}
      - action: script.comandi_zone_radio_non_pronta_pronta
        data: {}
      - action: script.comandi_zone_radio_allarme_no_allarme
        data: {}
      - action: script.stati_diagnostici
        data: {}
      - action: script.comandi_aree_non_pronte
        data: {}
      - action: script.comandi_aree_in_allarme
        data: {}
      mode: single
